/*
 * Copyright (c) 2023 Adevinta
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
@file:Suppress("UnusedReceiverParameter", "unused", "ktlint")

package com.adevinta.spark.icons

import com.adevinta.spark.icons.SparkIcon.Resource

/**
 * A collection of static icons from Spark.
 *
 * This object provides access to all static vector icons as drawable resources.
 * Each icon is available as a property that returns a [SparkIcon.DrawableRes] or a [SparkIcon.Vector],
 * ensuring type safety and consistency across the icon system.
 *
 * @see SparkIcon.DrawableRes
 * @see SparkIcon.Vector
 */
public object SparkIcons

public val SparkIcons.Accessories: Resource get() = Resource(Res.drawable.spark_icons_accessories)
public val SparkIcons.AccountFill: Resource get() = Resource(Res.drawable.spark_icons_account_fill)
public val SparkIcons.AccountOutline: Resource get() = Resource(Res.drawable.spark_icons_account_outline)
public val SparkIcons.Activity: Resource get() = Resource(Res.drawable.spark_icons_activity)
public val SparkIcons.AddFill: Resource get() = Resource(Res.drawable.spark_icons_add_fill)
public val SparkIcons.AddImageFill: Resource get() = Resource(Res.drawable.spark_icons_add_image_fill)
public val SparkIcons.AddImageOutline: Resource get() = Resource(Res.drawable.spark_icons_add_image_outline)
public val SparkIcons.AddOutline: Resource get() = Resource(Res.drawable.spark_icons_add_outline)
public val SparkIcons.AddSquareFill: Resource get() = Resource(Res.drawable.spark_icons_add_square_fill)
public val SparkIcons.AddSquareOutline: Resource get() = Resource(Res.drawable.spark_icons_add_square_outline)
public val SparkIcons.Age: Resource get() = Resource(Res.drawable.spark_icons_age)
public val SparkIcons.AirConditioning: Resource get() = Resource(Res.drawable.spark_icons_air_conditioning)
public val SparkIcons.AlarmFill: Resource get() = Resource(Res.drawable.spark_icons_alarm_fill)
public val SparkIcons.AlarmOffFill: Resource get() = Resource(Res.drawable.spark_icons_alarm_off_fill)
public val SparkIcons.AlarmOffOutline: Resource get() = Resource(Res.drawable.spark_icons_alarm_off_outline)
public val SparkIcons.AlarmOnFill: Resource get() = Resource(Res.drawable.spark_icons_alarm_on_fill)
public val SparkIcons.AlarmOnOutline: Resource get() = Resource(Res.drawable.spark_icons_alarm_on_outline)
public val SparkIcons.AlarmOutline: Resource get() = Resource(Res.drawable.spark_icons_alarm_outline)
public val SparkIcons.AlertFill: Resource get() = Resource(Res.drawable.spark_icons_alert_fill)
public val SparkIcons.AlertOutline: Resource get() = Resource(Res.drawable.spark_icons_alert_outline)
public val SparkIcons.AllDirection: Resource get() = Resource(Res.drawable.spark_icons_all_direction)
public val SparkIcons.Animals: Resource get() = Resource(Res.drawable.spark_icons_animals)
public val SparkIcons.Apartment: Resource get() = Resource(Res.drawable.spark_icons_apartment)
public val SparkIcons.Appearance: Resource get() = Resource(Res.drawable.spark_icons_appearance)
public val SparkIcons.Arrival: Resource get() = Resource(Res.drawable.spark_icons_arrival)
public val SparkIcons.ArrowDoubleLeft: Resource get() = Resource(Res.drawable.spark_icons_arrow_double_left)
public val SparkIcons.ArrowDoubleRight: Resource get() = Resource(Res.drawable.spark_icons_arrow_double_right)
public val SparkIcons.ArrowHorizontalDown: Resource get() = Resource(Res.drawable.spark_icons_arrow_horizontal_down)
public val SparkIcons.ArrowHorizontalUp: Resource get() = Resource(Res.drawable.spark_icons_arrow_horizontal_up)
public val SparkIcons.ArrowLeft: Resource get() = Resource(Res.drawable.spark_icons_arrow_left)
public val SparkIcons.ArrowRight: Resource get() = Resource(Res.drawable.spark_icons_arrow_right)
public val SparkIcons.ArrowVerticalLeft: Resource get() = Resource(Res.drawable.spark_icons_arrow_vertical_left)
public val SparkIcons.ArrowVerticalRight: Resource get() = Resource(Res.drawable.spark_icons_arrow_vertical_right)
public val SparkIcons.AttachFile: Resource get() = Resource(Res.drawable.spark_icons_attach_file)
public val SparkIcons.Attic: Resource get() = Resource(Res.drawable.spark_icons_attic)
public val SparkIcons.Available: Resource get() = Resource(Res.drawable.spark_icons_available)
public val SparkIcons.Axles: Resource get() = Resource(Res.drawable.spark_icons_axles)
public val SparkIcons.Baby: Resource get() = Resource(Res.drawable.spark_icons_baby)
public val SparkIcons.BabyFurniture: Resource get() = Resource(Res.drawable.spark_icons_baby_furniture)
public val SparkIcons.Balcony: Resource get() = Resource(Res.drawable.spark_icons_balcony)
public val SparkIcons.BankFill: Resource get() = Resource(Res.drawable.spark_icons_bank_fill)
public val SparkIcons.BankOutline: Resource get() = Resource(Res.drawable.spark_icons_bank_outline)
public val SparkIcons.Basement: Resource get() = Resource(Res.drawable.spark_icons_basement)
public val SparkIcons.BatchPurchase: Resource get() = Resource(Res.drawable.spark_icons_batch_purchase)
public val SparkIcons.Bath: Resource get() = Resource(Res.drawable.spark_icons_bath)
public val SparkIcons.BeautifulBuilding: Resource get() = Resource(Res.drawable.spark_icons_beautiful_building)
public val SparkIcons.BicycleType: Resource get() = Resource(Res.drawable.spark_icons_bicycle_type)
public val SparkIcons.Bike: Resource get() = Resource(Res.drawable.spark_icons_bike)
public val SparkIcons.BikeSize: Resource get() = Resource(Res.drawable.spark_icons_bike_size)
public val SparkIcons.Block: Resource get() = Resource(Res.drawable.spark_icons_block)
public val SparkIcons.Bluetooth: Resource get() = Resource(Res.drawable.spark_icons_bluetooth)
public val SparkIcons.Boat: Resource get() = Resource(Res.drawable.spark_icons_boat)
public val SparkIcons.Book: Resource get() = Resource(Res.drawable.spark_icons_book)
public val SparkIcons.BookmarkFill: Resource get() = Resource(Res.drawable.spark_icons_bookmark_fill)
public val SparkIcons.BookmarkOutline: Resource get() = Resource(Res.drawable.spark_icons_bookmark_outline)
public val SparkIcons.Booster: Resource get() = Resource(Res.drawable.spark_icons_booster)
public val SparkIcons.BoxFill: Resource get() = Resource(Res.drawable.spark_icons_box_fill)
public val SparkIcons.BoxOutline: Resource get() = Resource(Res.drawable.spark_icons_box_outline)
public val SparkIcons.Brand: Resource get() = Resource(Res.drawable.spark_icons_brand)
public val SparkIcons.Breakfast: Resource get() = Resource(Res.drawable.spark_icons_breakfast)
public val SparkIcons.Bump: Resource get() = Resource(Res.drawable.spark_icons_bump)
public val SparkIcons.BurgerMenu: Resource get() = Resource(Res.drawable.spark_icons_burger_menu)
public val SparkIcons.CalculateFill: Resource get() = Resource(Res.drawable.spark_icons_calculate_fill)
public val SparkIcons.CalculateOutline: Resource get() = Resource(Res.drawable.spark_icons_calculate_outline)
public val SparkIcons.CalendarCriterias: Resource get() = Resource(Res.drawable.spark_icons_calendar_criterias)
public val SparkIcons.CalendarDotFill: Resource get() = Resource(Res.drawable.spark_icons_calendar_dot_fill)
public val SparkIcons.CalendarDotOutline: Resource get() = Resource(Res.drawable.spark_icons_calendar_dot_outline)
public val SparkIcons.CalendarFill: Resource get() = Resource(Res.drawable.spark_icons_calendar_fill)
public val SparkIcons.CalendarOutline: Resource get() = Resource(Res.drawable.spark_icons_calendar_outline)
public val SparkIcons.CalendarValidFill: Resource get() = Resource(Res.drawable.spark_icons_calendar_valid_fill)
public val SparkIcons.CalendarValidOutline: Resource get() = Resource(Res.drawable.spark_icons_calendar_valid_outline)
public val SparkIcons.CallEnterFill: Resource get() = Resource(Res.drawable.spark_icons_call_enter_fill)
public val SparkIcons.CallEnterOutline: Resource get() = Resource(Res.drawable.spark_icons_call_enter_outline)
public val SparkIcons.CallFill: Resource get() = Resource(Res.drawable.spark_icons_call_fill)
public val SparkIcons.CallMissFill: Resource get() = Resource(Res.drawable.spark_icons_call_miss_fill)
public val SparkIcons.CallMissOutline: Resource get() = Resource(Res.drawable.spark_icons_call_miss_outline)
public val SparkIcons.CallOutline: Resource get() = Resource(Res.drawable.spark_icons_call_outline)
public val SparkIcons.Calm: Resource get() = Resource(Res.drawable.spark_icons_calm)
public val SparkIcons.CameraFill: Resource get() = Resource(Res.drawable.spark_icons_camera_fill)
public val SparkIcons.CameraOutline: Resource get() = Resource(Res.drawable.spark_icons_camera_outline)
public val SparkIcons.CameraVideo: Resource get() = Resource(Res.drawable.spark_icons_camera_video)
public val SparkIcons.Capacity: Resource get() = Resource(Res.drawable.spark_icons_capacity)
public val SparkIcons.CarBrand: Resource get() = Resource(Res.drawable.spark_icons_car_brand)
public val SparkIcons.CarFill: Resource get() = Resource(Res.drawable.spark_icons_car_fill)
public val SparkIcons.CarOutline: Resource get() = Resource(Res.drawable.spark_icons_car_outline)
public val SparkIcons.CarType: Resource get() = Resource(Res.drawable.spark_icons_car_type)
public val SparkIcons.CarWarrantyFill: Resource get() = Resource(Res.drawable.spark_icons_car_warranty_fill)
public val SparkIcons.CarWarrantyOutline: Resource get() = Resource(Res.drawable.spark_icons_car_warranty_outline)
public val SparkIcons.Card: Resource get() = Resource(Res.drawable.spark_icons_card)
public val SparkIcons.CardFill: Resource get() = Resource(Res.drawable.spark_icons_card_fill)
public val SparkIcons.CardOutline: Resource get() = Resource(Res.drawable.spark_icons_card_outline)
public val SparkIcons.CategoriesClothes: Resource get() = Resource(Res.drawable.spark_icons_categories_clothes)
public val SparkIcons.Cave: Resource get() = Resource(Res.drawable.spark_icons_cave)
public val SparkIcons.ChargesIncluded: Resource get() = Resource(Res.drawable.spark_icons_charges_included)
public val SparkIcons.Check: Resource get() = Resource(Res.drawable.spark_icons_check)
public val SparkIcons.Class: Resource get() = Resource(Res.drawable.spark_icons_class)
public val SparkIcons.Clean: Resource get() = Resource(Res.drawable.spark_icons_clean)
public val SparkIcons.ClockArrow: Resource get() = Resource(Res.drawable.spark_icons_clock_arrow)
public val SparkIcons.ClockFill: Resource get() = Resource(Res.drawable.spark_icons_clock_fill)
public val SparkIcons.ClockOutline: Resource get() = Resource(Res.drawable.spark_icons_clock_outline)
public val SparkIcons.Close: Resource get() = Resource(Res.drawable.spark_icons_close)
public val SparkIcons.Clothes: Resource get() = Resource(Res.drawable.spark_icons_clothes)
public val SparkIcons.ClothesBrand: Resource get() = Resource(Res.drawable.spark_icons_clothes_brand)
public val SparkIcons.ClothesCondition: Resource get() = Resource(Res.drawable.spark_icons_clothes_condition)
public val SparkIcons.Collectible: Resource get() = Resource(Res.drawable.spark_icons_collectible)
public val SparkIcons.Color: Resource get() = Resource(Res.drawable.spark_icons_color)
public val SparkIcons.Common: Resource get() = Resource(Res.drawable.spark_icons_common)
public val SparkIcons.Computer: Resource get() = Resource(Res.drawable.spark_icons_computer)
public val SparkIcons.ComputerAccessory: Resource get() = Resource(Res.drawable.spark_icons_computer_accessory)
public val SparkIcons.Condition: Resource get() = Resource(Res.drawable.spark_icons_condition)
public val SparkIcons.ConversationFill: Resource get() = Resource(Res.drawable.spark_icons_conversation_fill)
public val SparkIcons.ConversationOutline: Resource get() = Resource(Res.drawable.spark_icons_conversation_outline)
public val SparkIcons.CopyFill: Resource get() = Resource(Res.drawable.spark_icons_copy_fill)
public val SparkIcons.CopyOutline: Resource get() = Resource(Res.drawable.spark_icons_copy_outline)
public val SparkIcons.Couch: Resource get() = Resource(Res.drawable.spark_icons_couch)
public val SparkIcons.CountryFill: Resource get() = Resource(Res.drawable.spark_icons_country_fill)
public val SparkIcons.CountryOutline: Resource get() = Resource(Res.drawable.spark_icons_country_outline)
public val SparkIcons.Crop: Resource get() = Resource(Res.drawable.spark_icons_crop)
public val SparkIcons.CvFill: Resource get() = Resource(Res.drawable.spark_icons_cv_fill)
public val SparkIcons.CvOutline: Resource get() = Resource(Res.drawable.spark_icons_cv_outline)
public val SparkIcons.Cylindrical: Resource get() = Resource(Res.drawable.spark_icons_cylindrical)
public val SparkIcons.DarkMode: Resource get() = Resource(Res.drawable.spark_icons_dark_mode)
public val SparkIcons.DeleteFill: Resource get() = Resource(Res.drawable.spark_icons_delete_fill)
public val SparkIcons.DeleteOutline: Resource get() = Resource(Res.drawable.spark_icons_delete_outline)
public val SparkIcons.Delivery: Resource get() = Resource(Res.drawable.spark_icons_delivery)
public val SparkIcons.DeliveryFastFill: Resource get() = Resource(Res.drawable.spark_icons_delivery_fast_fill)
public val SparkIcons.DeliveryFastOutline: Resource get() = Resource(Res.drawable.spark_icons_delivery_fast_outline)
public val SparkIcons.DeliveryFill: Resource get() = Resource(Res.drawable.spark_icons_delivery_fill)
public val SparkIcons.DeliveryHandsFill: Resource get() = Resource(Res.drawable.spark_icons_delivery_hands_fill)
public val SparkIcons.DeliveryHandsOutline: Resource
    get() =
        Resource(Res.drawable.spark_icons_delivery_hands_outline)
public val SparkIcons.DeliveryOutline: Resource get() = Resource(Res.drawable.spark_icons_delivery_outline)
public val SparkIcons.DeliveryTruckFill: Resource get() = Resource(Res.drawable.spark_icons_delivery_truck_fill)
public val SparkIcons.DeliveryTruckOutline: Resource
    get() =
        Resource(Res.drawable.spark_icons_delivery_truck_outline)
public val SparkIcons.Digicode: Resource get() = Resource(Res.drawable.spark_icons_digicode)
public val SparkIcons.Directory: Resource get() = Resource(Res.drawable.spark_icons_directory)
public val SparkIcons.DissatisfiedFill: Resource get() = Resource(Res.drawable.spark_icons_dissatisfied_fill)
public val SparkIcons.DissatisfiedOutline: Resource get() = Resource(Res.drawable.spark_icons_dissatisfied_outline)
public val SparkIcons.DiyProduct: Resource get() = Resource(Res.drawable.spark_icons_diy_product)
public val SparkIcons.DiyType: Resource get() = Resource(Res.drawable.spark_icons_diy_type)
public val SparkIcons.Donate: Resource get() = Resource(Res.drawable.spark_icons_donate)
public val SparkIcons.Donation: Resource get() = Resource(Res.drawable.spark_icons_donation)
public val SparkIcons.Doors: Resource get() = Resource(Res.drawable.spark_icons_doors)
public val SparkIcons.DoubleCheck: Resource get() = Resource(Res.drawable.spark_icons_double_check)
public val SparkIcons.DownloadFill: Resource get() = Resource(Res.drawable.spark_icons_download_fill)
public val SparkIcons.DownloadOutline: Resource get() = Resource(Res.drawable.spark_icons_download_outline)
public val SparkIcons.Dress: Resource get() = Resource(Res.drawable.spark_icons_dress)
public val SparkIcons.DumpTruck: Resource get() = Resource(Res.drawable.spark_icons_dump_truck)
public val SparkIcons.Duplex: Resource get() = Resource(Res.drawable.spark_icons_duplex)
public val SparkIcons.EducationalLevel: Resource get() = Resource(Res.drawable.spark_icons_educational_level)
public val SparkIcons.Energy: Resource get() = Resource(Res.drawable.spark_icons_energy)
public val SparkIcons.EngineStart: Resource get() = Resource(Res.drawable.spark_icons_engine_start)
public val SparkIcons.Equipment: Resource get() = Resource(Res.drawable.spark_icons_equipment)
public val SparkIcons.EquipmentBaby: Resource get() = Resource(Res.drawable.spark_icons_equipment_baby)
public val SparkIcons.ErrorPhoto: Resource get() = Resource(Res.drawable.spark_icons_error_photo)
public val SparkIcons.Euro: Resource get() = Resource(Res.drawable.spark_icons_euro)
public val SparkIcons.Experience: Resource get() = Resource(Res.drawable.spark_icons_experience)
public val SparkIcons.Export: Resource get() = Resource(Res.drawable.spark_icons_export)
public val SparkIcons.EyeFill: Resource get() = Resource(Res.drawable.spark_icons_eye_fill)
public val SparkIcons.EyeOffFill: Resource get() = Resource(Res.drawable.spark_icons_eye_off_fill)
public val SparkIcons.EyeOffOutline: Resource get() = Resource(Res.drawable.spark_icons_eye_off_outline)
public val SparkIcons.EyeOutline: Resource get() = Resource(Res.drawable.spark_icons_eye_outline)
public val SparkIcons.FacebookFill: Resource get() = Resource(Res.drawable.spark_icons_facebook_fill)
public val SparkIcons.FacebookOutline: Resource get() = Resource(Res.drawable.spark_icons_facebook_outline)
public val SparkIcons.Family: Resource get() = Resource(Res.drawable.spark_icons_family)
public val SparkIcons.FavoriteFill: Resource get() = Resource(Res.drawable.spark_icons_favorite_fill)
public val SparkIcons.FavoriteOutline: Resource get() = Resource(Res.drawable.spark_icons_favorite_outline)
public val SparkIcons.FeedbackFill: Resource get() = Resource(Res.drawable.spark_icons_feedback_fill)
public val SparkIcons.FeedbackOutline: Resource get() = Resource(Res.drawable.spark_icons_feedback_outline)
public val SparkIcons.FileOffFill: Resource get() = Resource(Res.drawable.spark_icons_file_off_fill)
public val SparkIcons.FileOffOutline: Resource get() = Resource(Res.drawable.spark_icons_file_off_outline)
public val SparkIcons.FilePdfFill: Resource get() = Resource(Res.drawable.spark_icons_file_pdf_fill)
public val SparkIcons.FilePdfOutline: Resource get() = Resource(Res.drawable.spark_icons_file_pdf_outline)
public val SparkIcons.Filter: Resource get() = Resource(Res.drawable.spark_icons_filter)
public val SparkIcons.FireFill: Resource get() = Resource(Res.drawable.spark_icons_fire_fill)
public val SparkIcons.FireOutline: Resource get() = Resource(Res.drawable.spark_icons_fire_outline)
public val SparkIcons.Fireplace: Resource get() = Resource(Res.drawable.spark_icons_fireplace)
public val SparkIcons.FlagFill: Resource get() = Resource(Res.drawable.spark_icons_flag_fill)
public val SparkIcons.FlagOutline: Resource get() = Resource(Res.drawable.spark_icons_flag_outline)
public val SparkIcons.FlashFill: Resource get() = Resource(Res.drawable.spark_icons_flash_fill)
public val SparkIcons.FlashOutline: Resource get() = Resource(Res.drawable.spark_icons_flash_outline)
public val SparkIcons.FlashlightFill: Resource get() = Resource(Res.drawable.spark_icons_flashlight_fill)
public val SparkIcons.FlashlightOutline: Resource get() = Resource(Res.drawable.spark_icons_flashlight_outline)
public val SparkIcons.Floor: Resource get() = Resource(Res.drawable.spark_icons_floor)
public val SparkIcons.ForwardFill: Resource get() = Resource(Res.drawable.spark_icons_forward_fill)
public val SparkIcons.ForwardOutline: Resource get() = Resource(Res.drawable.spark_icons_forward_outline)
public val SparkIcons.Fuel: Resource get() = Resource(Res.drawable.spark_icons_fuel)
public val SparkIcons.Function: Resource get() = Resource(Res.drawable.spark_icons_function)
public val SparkIcons.Furniture: Resource get() = Resource(Res.drawable.spark_icons_furniture)
public val SparkIcons.FurnitureType: Resource get() = Resource(Res.drawable.spark_icons_furniture_type)
public val SparkIcons.GalleryFill: Resource get() = Resource(Res.drawable.spark_icons_gallery_fill)
public val SparkIcons.GalleryOutline: Resource get() = Resource(Res.drawable.spark_icons_gallery_outline)
public val SparkIcons.Garage: Resource get() = Resource(Res.drawable.spark_icons_garage)
public val SparkIcons.Garden: Resource get() = Resource(Res.drawable.spark_icons_garden)
public val SparkIcons.GardeningProduct: Resource get() = Resource(Res.drawable.spark_icons_gardening_product)
public val SparkIcons.GardeningType: Resource get() = Resource(Res.drawable.spark_icons_gardening_type)
public val SparkIcons.GlassWindows: Resource get() = Resource(Res.drawable.spark_icons_glass_windows)
public val SparkIcons.Gps: Resource get() = Resource(Res.drawable.spark_icons_gps)
public val SparkIcons.GraphArrowDown: Resource get() = Resource(Res.drawable.spark_icons_graph_arrow_down)
public val SparkIcons.GraphArrowUp: Resource get() = Resource(Res.drawable.spark_icons_graph_arrow_up)
public val SparkIcons.GraphFill: Resource get() = Resource(Res.drawable.spark_icons_graph_fill)
public val SparkIcons.GraphOutline: Resource get() = Resource(Res.drawable.spark_icons_graph_outline)
public val SparkIcons.Ground: Resource get() = Resource(Res.drawable.spark_icons_ground)
public val SparkIcons.GroupFill: Resource get() = Resource(Res.drawable.spark_icons_group_fill)
public val SparkIcons.GroupOutline: Resource get() = Resource(Res.drawable.spark_icons_group_outline)
public val SparkIcons.HandDelivered: Resource get() = Resource(Res.drawable.spark_icons_hand_delivered)
public val SparkIcons.Headlight: Resource get() = Resource(Res.drawable.spark_icons_headlight)
public val SparkIcons.Highlight: Resource get() = Resource(Res.drawable.spark_icons_highlight)
public val SparkIcons.Hobby: Resource get() = Resource(Res.drawable.spark_icons_hobby)
public val SparkIcons.HolidayFill: Resource get() = Resource(Res.drawable.spark_icons_holiday_fill)
public val SparkIcons.HolidayOutline: Resource get() = Resource(Res.drawable.spark_icons_holiday_outline)
public val SparkIcons.Holidays: Resource get() = Resource(Res.drawable.spark_icons_holidays)
public val SparkIcons.HolidaysGarden: Resource get() = Resource(Res.drawable.spark_icons_holidays_garden)
public val SparkIcons.HomeFill: Resource get() = Resource(Res.drawable.spark_icons_home_fill)
public val SparkIcons.HomeOutline: Resource get() = Resource(Res.drawable.spark_icons_home_outline)
public val SparkIcons.HomeappliancesProduct: Resource
    get() =
        Resource(Res.drawable.spark_icons_homeappliances_product)
public val SparkIcons.HomeappliancesType: Resource
    get() =
        Resource(Res.drawable.spark_icons_homeappliances_type)
public val SparkIcons.Honoraria: Resource get() = Resource(Res.drawable.spark_icons_honoraria)
public val SparkIcons.HotelFill: Resource get() = Resource(Res.drawable.spark_icons_hotel_fill)
public val SparkIcons.HotelOutline: Resource get() = Resource(Res.drawable.spark_icons_hotel_outline)
public val SparkIcons.House: Resource get() = Resource(Res.drawable.spark_icons_house)
public val SparkIcons.HousingType: Resource get() = Resource(Res.drawable.spark_icons_housing_type)
public val SparkIcons.IdeaFill: Resource get() = Resource(Res.drawable.spark_icons_idea_fill)
public val SparkIcons.IdeaOutline: Resource get() = Resource(Res.drawable.spark_icons_idea_outline)
public val SparkIcons.IdentityFill: Resource get() = Resource(Res.drawable.spark_icons_identity_fill)
public val SparkIcons.IdentityOutline: Resource get() = Resource(Res.drawable.spark_icons_identity_outline)
public val SparkIcons.ImageFill: Resource get() = Resource(Res.drawable.spark_icons_image_fill)
public val SparkIcons.ImageOutline: Resource get() = Resource(Res.drawable.spark_icons_image_outline)
public val SparkIcons.Import: Resource get() = Resource(Res.drawable.spark_icons_import)
public val SparkIcons.InfoFill: Resource get() = Resource(Res.drawable.spark_icons_info_fill)
public val SparkIcons.InfoOutline: Resource get() = Resource(Res.drawable.spark_icons_info_outline)
public val SparkIcons.InstagramFill: Resource get() = Resource(Res.drawable.spark_icons_instagram_fill)
public val SparkIcons.InstagramOutline: Resource get() = Resource(Res.drawable.spark_icons_instagram_outline)
public val SparkIcons.Interphone: Resource get() = Resource(Res.drawable.spark_icons_interphone)
public val SparkIcons.Janitor: Resource get() = Resource(Res.drawable.spark_icons_janitor)
public val SparkIcons.Jewels: Resource get() = Resource(Res.drawable.spark_icons_jewels)
public val SparkIcons.Job: Resource get() = Resource(Res.drawable.spark_icons_job)
public val SparkIcons.JobType: Resource get() = Resource(Res.drawable.spark_icons_job_type)
public val SparkIcons.KeyFill: Resource get() = Resource(Res.drawable.spark_icons_key_fill)
public val SparkIcons.KeyOutline: Resource get() = Resource(Res.drawable.spark_icons_key_outline)
public val SparkIcons.KeylessAccess: Resource get() = Resource(Res.drawable.spark_icons_keyless_access)
public val SparkIcons.Land: Resource get() = Resource(Res.drawable.spark_icons_land)
public val SparkIcons.LastFloor: Resource get() = Resource(Res.drawable.spark_icons_last_floor)
public val SparkIcons.Lens: Resource get() = Resource(Res.drawable.spark_icons_lens)
public val SparkIcons.License: Resource get() = Resource(Res.drawable.spark_icons_license)
public val SparkIcons.Lift: Resource get() = Resource(Res.drawable.spark_icons_lift)
public val SparkIcons.Light: Resource get() = Resource(Res.drawable.spark_icons_light)
public val SparkIcons.LightMode: Resource get() = Resource(Res.drawable.spark_icons_light_mode)
public val SparkIcons.Like: Resource get() = Resource(Res.drawable.spark_icons_like)
public val SparkIcons.LikeFill: Resource get() = Resource(Res.drawable.spark_icons_like_fill)
public val SparkIcons.LikeOutline: Resource get() = Resource(Res.drawable.spark_icons_like_outline)
public val SparkIcons.LinensProduct: Resource get() = Resource(Res.drawable.spark_icons_linens_product)
public val SparkIcons.LinensType: Resource get() = Resource(Res.drawable.spark_icons_linens_type)
public val SparkIcons.Link: Resource get() = Resource(Res.drawable.spark_icons_link)
public val SparkIcons.Linkedin: Resource get() = Resource(Res.drawable.spark_icons_linkedin)
public val SparkIcons.Listing: Resource get() = Resource(Res.drawable.spark_icons_listing)
public val SparkIcons.Litter: Resource get() = Resource(Res.drawable.spark_icons_litter)
public val SparkIcons.Loader: Resource get() = Resource(Res.drawable.spark_icons_loader)
public val SparkIcons.Localisation: Resource get() = Resource(Res.drawable.spark_icons_localisation)
public val SparkIcons.LockFill: Resource get() = Resource(Res.drawable.spark_icons_lock_fill)
public val SparkIcons.LockOutline: Resource get() = Resource(Res.drawable.spark_icons_lock_outline)
public val SparkIcons.Loft: Resource get() = Resource(Res.drawable.spark_icons_loft)
public val SparkIcons.Loggia: Resource get() = Resource(Res.drawable.spark_icons_loggia)
public val SparkIcons.Loof: Resource get() = Resource(Res.drawable.spark_icons_loof)
public val SparkIcons.Luxe: Resource get() = Resource(Res.drawable.spark_icons_luxe)
public val SparkIcons.MailCloseFill: Resource get() = Resource(Res.drawable.spark_icons_mail_close_fill)
public val SparkIcons.MailCloseOutline: Resource get() = Resource(Res.drawable.spark_icons_mail_close_outline)
public val SparkIcons.MailFill: Resource get() = Resource(Res.drawable.spark_icons_mail_fill)
public val SparkIcons.MailOpenFill: Resource get() = Resource(Res.drawable.spark_icons_mail_open_fill)
public val SparkIcons.MailOpenOutline: Resource get() = Resource(Res.drawable.spark_icons_mail_open_outline)
public val SparkIcons.MailOutline: Resource get() = Resource(Res.drawable.spark_icons_mail_outline)
public val SparkIcons.MapCursorFill: Resource get() = Resource(Res.drawable.spark_icons_map_cursor_fill)
public val SparkIcons.MapCursorOutline: Resource get() = Resource(Res.drawable.spark_icons_map_cursor_outline)
public val SparkIcons.MapExpand: Resource get() = Resource(Res.drawable.spark_icons_map_expand)
public val SparkIcons.Material: Resource get() = Resource(Res.drawable.spark_icons_material)
public val SparkIcons.MegaphoneFill: Resource get() = Resource(Res.drawable.spark_icons_megaphone_fill)
public val SparkIcons.MegaphoneMuteFill: Resource get() = Resource(Res.drawable.spark_icons_megaphone_mute_fill)
public val SparkIcons.MegaphoneMuteOutline: Resource
    get() =
        Resource(Res.drawable.spark_icons_megaphone_mute_outline)
public val SparkIcons.MegaphoneOutline: Resource get() = Resource(Res.drawable.spark_icons_megaphone_outline)
public val SparkIcons.Memory: Resource get() = Resource(Res.drawable.spark_icons_memory)
public val SparkIcons.MessageFill: Resource get() = Resource(Res.drawable.spark_icons_message_fill)
public val SparkIcons.MessageOutline: Resource get() = Resource(Res.drawable.spark_icons_message_outline)
public val SparkIcons.Messenger: Resource get() = Resource(Res.drawable.spark_icons_messenger)
public val SparkIcons.Metro: Resource get() = Resource(Res.drawable.spark_icons_metro)
public val SparkIcons.Mileage: Resource get() = Resource(Res.drawable.spark_icons_mileage)
public val SparkIcons.Minus: Resource get() = Resource(Res.drawable.spark_icons_minus)
public val SparkIcons.MobileCheck: Resource get() = Resource(Res.drawable.spark_icons_mobile_check)
public val SparkIcons.Model: Resource get() = Resource(Res.drawable.spark_icons_model)
public val SparkIcons.MoneyFill: Resource get() = Resource(Res.drawable.spark_icons_money_fill)
public val SparkIcons.MoneyOutline: Resource get() = Resource(Res.drawable.spark_icons_money_outline)
public val SparkIcons.MoreMenuHorizontal: Resource get() = Resource(Res.drawable.spark_icons_more_menu_horizontal)
public val SparkIcons.MoreMenuVertical: Resource get() = Resource(Res.drawable.spark_icons_more_menu_vertical)
public val SparkIcons.Moto: Resource get() = Resource(Res.drawable.spark_icons_moto)
public val SparkIcons.Moulding: Resource get() = Resource(Res.drawable.spark_icons_moulding)
public val SparkIcons.MoveUp: Resource get() = Resource(Res.drawable.spark_icons_move_up)
public val SparkIcons.Multimedia: Resource get() = Resource(Res.drawable.spark_icons_multimedia)
public val SparkIcons.MultimediaSystem: Resource get() = Resource(Res.drawable.spark_icons_multimedia_system)
public val SparkIcons.NeutralFill: Resource get() = Resource(Res.drawable.spark_icons_neutral_fill)
public val SparkIcons.NeutralOutline: Resource get() = Resource(Res.drawable.spark_icons_neutral_outline)
public val SparkIcons.NoPhoto: Resource get() = Resource(Res.drawable.spark_icons_no_photo)
public val SparkIcons.NotificationFill: Resource get() = Resource(Res.drawable.spark_icons_notification_fill)
public val SparkIcons.NotificationOutline: Resource get() = Resource(Res.drawable.spark_icons_notification_outline)
public val SparkIcons.Offer: Resource get() = Resource(Res.drawable.spark_icons_offer)
public val SparkIcons.OfferFill: Resource get() = Resource(Res.drawable.spark_icons_offer_fill)
public val SparkIcons.OfferOutline: Resource get() = Resource(Res.drawable.spark_icons_offer_outline)
public val SparkIcons.OfferType: Resource get() = Resource(Res.drawable.spark_icons_offer_type)
public val SparkIcons.PaperMapFill: Resource get() = Resource(Res.drawable.spark_icons_paper_map_fill)
public val SparkIcons.PaperMapOutline: Resource get() = Resource(Res.drawable.spark_icons_paper_map_outline)
public val SparkIcons.ParkAssist: Resource get() = Resource(Res.drawable.spark_icons_park_assist)
public val SparkIcons.Parking: Resource get() = Resource(Res.drawable.spark_icons_parking)
public val SparkIcons.ParkingEstate: Resource get() = Resource(Res.drawable.spark_icons_parking_estate)
public val SparkIcons.ParkingSensor: Resource get() = Resource(Res.drawable.spark_icons_parking_sensor)
public val SparkIcons.Parquet: Resource get() = Resource(Res.drawable.spark_icons_parquet)
public val SparkIcons.PauseFill: Resource get() = Resource(Res.drawable.spark_icons_pause_fill)
public val SparkIcons.PauseOutline: Resource get() = Resource(Res.drawable.spark_icons_pause_outline)
public val SparkIcons.PenFill: Resource get() = Resource(Res.drawable.spark_icons_pen_fill)
public val SparkIcons.PenOutline: Resource get() = Resource(Res.drawable.spark_icons_pen_outline)
public val SparkIcons.Percentage: Resource get() = Resource(Res.drawable.spark_icons_percentage)
public val SparkIcons.PetAccessory: Resource get() = Resource(Res.drawable.spark_icons_pet_accessory)
public val SparkIcons.Pets: Resource get() = Resource(Res.drawable.spark_icons_pets)
public val SparkIcons.PhoneFill: Resource get() = Resource(Res.drawable.spark_icons_phone_fill)
public val SparkIcons.PhoneOutline: Resource get() = Resource(Res.drawable.spark_icons_phone_outline)
public val SparkIcons.PhotoPack: Resource get() = Resource(Res.drawable.spark_icons_photo_pack)
public val SparkIcons.Pieces: Resource get() = Resource(Res.drawable.spark_icons_pieces)
public val SparkIcons.PiggyBankFill: Resource get() = Resource(Res.drawable.spark_icons_piggy_bank_fill)
public val SparkIcons.PiggyBankOutline: Resource get() = Resource(Res.drawable.spark_icons_piggy_bank_outline)
public val SparkIcons.PinFill: Resource get() = Resource(Res.drawable.spark_icons_pin_fill)
public val SparkIcons.PinOutline: Resource get() = Resource(Res.drawable.spark_icons_pin_outline)
public val SparkIcons.Pinterest: Resource get() = Resource(Res.drawable.spark_icons_pinterest)
public val SparkIcons.PlayFill: Resource get() = Resource(Res.drawable.spark_icons_play_fill)
public val SparkIcons.PlayOutline: Resource get() = Resource(Res.drawable.spark_icons_play_outline)
public val SparkIcons.Plus: Resource get() = Resource(Res.drawable.spark_icons_plus)
public val SparkIcons.Pool: Resource get() = Resource(Res.drawable.spark_icons_pool)
public val SparkIcons.Power: Resource get() = Resource(Res.drawable.spark_icons_power)
public val SparkIcons.PrintFill: Resource get() = Resource(Res.drawable.spark_icons_print_fill)
public val SparkIcons.PrintOutline: Resource get() = Resource(Res.drawable.spark_icons_print_outline)
public val SparkIcons.ProCursorFill: Resource get() = Resource(Res.drawable.spark_icons_pro_cursor_fill)
public val SparkIcons.ProCursorOutline: Resource get() = Resource(Res.drawable.spark_icons_pro_cursor_outline)
public val SparkIcons.ProFill: Resource get() = Resource(Res.drawable.spark_icons_pro_fill)
public val SparkIcons.ProOutline: Resource get() = Resource(Res.drawable.spark_icons_pro_outline)
public val SparkIcons.ProfileFill: Resource get() = Resource(Res.drawable.spark_icons_profile_fill)
public val SparkIcons.ProfileOutline: Resource get() = Resource(Res.drawable.spark_icons_profile_outline)
public val SparkIcons.QuestionFill: Resource get() = Resource(Res.drawable.spark_icons_question_fill)
public val SparkIcons.QuestionOutline: Resource get() = Resource(Res.drawable.spark_icons_question_outline)
public val SparkIcons.RainSensor: Resource get() = Resource(Res.drawable.spark_icons_rain_sensor)
public val SparkIcons.Rating: Resource get() = Resource(Res.drawable.spark_icons_rating)
public val SparkIcons.RearviewCamera: Resource get() = Resource(Res.drawable.spark_icons_rearview_camera)
public val SparkIcons.RearviewMirror: Resource get() = Resource(Res.drawable.spark_icons_rearview_mirror)
public val SparkIcons.Redo: Resource get() = Resource(Res.drawable.spark_icons_redo)
public val SparkIcons.Reference: Resource get() = Resource(Res.drawable.spark_icons_reference)
public val SparkIcons.Refresh: Resource get() = Resource(Res.drawable.spark_icons_refresh)
public val SparkIcons.Refund: Resource get() = Resource(Res.drawable.spark_icons_refund)
public val SparkIcons.RemoveFill: Resource get() = Resource(Res.drawable.spark_icons_remove_fill)
public val SparkIcons.RemoveOutline: Resource get() = Resource(Res.drawable.spark_icons_remove_outline)
public val SparkIcons.Renovation: Resource get() = Resource(Res.drawable.spark_icons_renovation)
public val SparkIcons.Rental: Resource get() = Resource(Res.drawable.spark_icons_rental)
public val SparkIcons.RocketFill: Resource get() = Resource(Res.drawable.spark_icons_rocket_fill)
public val SparkIcons.RocketOutline: Resource get() = Resource(Res.drawable.spark_icons_rocket_outline)
public val SparkIcons.Rooms: Resource get() = Resource(Res.drawable.spark_icons_rooms)
public val SparkIcons.RotateImage: Resource get() = Resource(Res.drawable.spark_icons_rotate_image)
public val SparkIcons.SadFill: Resource get() = Resource(Res.drawable.spark_icons_sad_fill)
public val SparkIcons.SadOutline: Resource get() = Resource(Res.drawable.spark_icons_sad_outline)
public val SparkIcons.Salary: Resource get() = Resource(Res.drawable.spark_icons_salary)
public val SparkIcons.SaleType: Resource get() = Resource(Res.drawable.spark_icons_sale_type)
public val SparkIcons.SatisfiedFill: Resource get() = Resource(Res.drawable.spark_icons_satisfied_fill)
public val SparkIcons.SatisfiedOutline: Resource get() = Resource(Res.drawable.spark_icons_satisfied_outline)
public val SparkIcons.Scan: Resource get() = Resource(Res.drawable.spark_icons_scan)
public val SparkIcons.SeaView: Resource get() = Resource(Res.drawable.spark_icons_sea_view)
public val SparkIcons.Search: Resource get() = Resource(Res.drawable.spark_icons_search)
public val SparkIcons.SearchFill: Resource get() = Resource(Res.drawable.spark_icons_search_fill)
public val SparkIcons.SearchOutline: Resource get() = Resource(Res.drawable.spark_icons_search_outline)
public val SparkIcons.Seat: Resource get() = Resource(Res.drawable.spark_icons_seat)
public val SparkIcons.Seats: Resource get() = Resource(Res.drawable.spark_icons_seats)
public val SparkIcons.Sector: Resource get() = Resource(Res.drawable.spark_icons_sector)
public val SparkIcons.SecurityFill: Resource get() = Resource(Res.drawable.spark_icons_security_fill)
public val SparkIcons.SecurityOutline: Resource get() = Resource(Res.drawable.spark_icons_security_outline)
public val SparkIcons.SecurityProfileAccountFill: Resource
    get() =
        Resource(Res.drawable.spark_icons_security_profile_account_fill)
public val SparkIcons.SecurityProfileAccountOutline: Resource
    get() =
        Resource(Res.drawable.spark_icons_security_profile_account_outline)
public val SparkIcons.SecurityProfileFill: Resource
    get() =
        Resource(Res.drawable.spark_icons_security_profile_fill)
public val SparkIcons.SecurityProfileOutline: Resource
    get() =
        Resource(Res.drawable.spark_icons_security_profile_outline)
public val SparkIcons.Seller: Resource get() = Resource(Res.drawable.spark_icons_seller)
public val SparkIcons.SendFill: Resource get() = Resource(Res.drawable.spark_icons_send_fill)
public val SparkIcons.SendHorizontal: Resource get() = Resource(Res.drawable.spark_icons_send_horizontal)
public val SparkIcons.SendOutline: Resource get() = Resource(Res.drawable.spark_icons_send_outline)
public val SparkIcons.Service: Resource get() = Resource(Res.drawable.spark_icons_service)
public val SparkIcons.ShareExpand: Resource get() = Resource(Res.drawable.spark_icons_share_expand)
public val SparkIcons.ShareFill: Resource get() = Resource(Res.drawable.spark_icons_share_fill)
public val SparkIcons.ShareOutline: Resource get() = Resource(Res.drawable.spark_icons_share_outline)
public val SparkIcons.ShareiOS: Resource get() = Resource(Res.drawable.spark_icons_sharei_o_s)
public val SparkIcons.ShoeSize: Resource get() = Resource(Res.drawable.spark_icons_shoe_size)
public val SparkIcons.Shoes: Resource get() = Resource(Res.drawable.spark_icons_shoes)
public val SparkIcons.ShoppingCartFill: Resource get() = Resource(Res.drawable.spark_icons_shopping_cart_fill)
public val SparkIcons.ShoppingCartOutline: Resource get() = Resource(Res.drawable.spark_icons_shopping_cart_outline)
public val SparkIcons.ShovelRake: Resource get() = Resource(Res.drawable.spark_icons_shovel_rake)
public val SparkIcons.Shower: Resource get() = Resource(Res.drawable.spark_icons_shower)
public val SparkIcons.Size: Resource get() = Resource(Res.drawable.spark_icons_size)
public val SparkIcons.Smoking: Resource get() = Resource(Res.drawable.spark_icons_smoking)
public val SparkIcons.Sort: Resource get() = Resource(Res.drawable.spark_icons_sort)
public val SparkIcons.SortFilled: Resource get() = Resource(Res.drawable.spark_icons_sort_filled)
public val SparkIcons.Spa: Resource get() = Resource(Res.drawable.spark_icons_spa)
public val SparkIcons.Speaker: Resource get() = Resource(Res.drawable.spark_icons_speaker)
public val SparkIcons.Speed: Resource get() = Resource(Res.drawable.spark_icons_speed)
public val SparkIcons.SpeedIndicator: Resource get() = Resource(Res.drawable.spark_icons_speed_indicator)
public val SparkIcons.SpeedmeterFill: Resource get() = Resource(Res.drawable.spark_icons_speedmeter_fill)
public val SparkIcons.SpeedmeterOutline: Resource get() = Resource(Res.drawable.spark_icons_speedmeter_outline)
public val SparkIcons.Sport: Resource get() = Resource(Res.drawable.spark_icons_sport)
public val SparkIcons.StarFill: Resource get() = Resource(Res.drawable.spark_icons_star_fill)
public val SparkIcons.StarOutline: Resource get() = Resource(Res.drawable.spark_icons_star_outline)
public val SparkIcons.Start: Resource get() = Resource(Res.drawable.spark_icons_start)
public val SparkIcons.Store: Resource get() = Resource(Res.drawable.spark_icons_store)
public val SparkIcons.StoreFill: Resource get() = Resource(Res.drawable.spark_icons_store_fill)
public val SparkIcons.StoreOutline: Resource get() = Resource(Res.drawable.spark_icons_store_outline)
public val SparkIcons.Sun: Resource get() = Resource(Res.drawable.spark_icons_sun)
public val SparkIcons.SunOrientation: Resource get() = Resource(Res.drawable.spark_icons_sun_orientation)
public val SparkIcons.Sunroof: Resource get() = Resource(Res.drawable.spark_icons_sunroof)
public val SparkIcons.SupportFill: Resource get() = Resource(Res.drawable.spark_icons_support_fill)
public val SparkIcons.SupportOutline: Resource get() = Resource(Res.drawable.spark_icons_support_outline)
public val SparkIcons.SupportSmileFill: Resource get() = Resource(Res.drawable.spark_icons_support_smile_fill)
public val SparkIcons.SupportSmileOutline: Resource get() = Resource(Res.drawable.spark_icons_support_smile_outline)
public val SparkIcons.Surface: Resource get() = Resource(Res.drawable.spark_icons_surface)
public val SparkIcons.TableArtMaterial: Resource get() = Resource(Res.drawable.spark_icons_table_art_material)
public val SparkIcons.TableArtProduct: Resource get() = Resource(Res.drawable.spark_icons_table_art_product)
public val SparkIcons.TargetFill: Resource get() = Resource(Res.drawable.spark_icons_target_fill)
public val SparkIcons.TargetOutline: Resource get() = Resource(Res.drawable.spark_icons_target_outline)
public val SparkIcons.Tattoo: Resource get() = Resource(Res.drawable.spark_icons_tattoo)
public val SparkIcons.Terrace: Resource get() = Resource(Res.drawable.spark_icons_terrace)
public val SparkIcons.ThreeD: Resource get() = Resource(Res.drawable.spark_icons_three_d)
public val SparkIcons.ThreeSixty: Resource get() = Resource(Res.drawable.spark_icons_three_sixty)
public val SparkIcons.Time: Resource get() = Resource(Res.drawable.spark_icons_time)
public val SparkIcons.Tools: Resource get() = Resource(Res.drawable.spark_icons_tools)
public val SparkIcons.TopAd: Resource get() = Resource(Res.drawable.spark_icons_top_ad)
public val SparkIcons.Toy: Resource get() = Resource(Res.drawable.spark_icons_toy)
public val SparkIcons.ToysProduct: Resource get() = Resource(Res.drawable.spark_icons_toys_product)
public val SparkIcons.Tractor: Resource get() = Resource(Res.drawable.spark_icons_tractor)
public val SparkIcons.TrainFill: Resource get() = Resource(Res.drawable.spark_icons_train_fill)
public val SparkIcons.TrainOutline: Resource get() = Resource(Res.drawable.spark_icons_train_outline)
public val SparkIcons.TrashCloseFill: Resource get() = Resource(Res.drawable.spark_icons_trash_close_fill)
public val SparkIcons.TrashCloseOutline: Resource get() = Resource(Res.drawable.spark_icons_trash_close_outline)
public val SparkIcons.TrashFill: Resource get() = Resource(Res.drawable.spark_icons_trash_fill)
public val SparkIcons.TrashOutline: Resource get() = Resource(Res.drawable.spark_icons_trash_outline)
public val SparkIcons.Truck: Resource get() = Resource(Res.drawable.spark_icons_truck)
public val SparkIcons.Trunk: Resource get() = Resource(Res.drawable.spark_icons_trunk)
public val SparkIcons.Tv: Resource get() = Resource(Res.drawable.spark_icons_tv)
public val SparkIcons.Twitter: Resource get() = Resource(Res.drawable.spark_icons_twitter)
public val SparkIcons.Type: Resource get() = Resource(Res.drawable.spark_icons_type)
public val SparkIcons.TypingFill: Resource get() = Resource(Res.drawable.spark_icons_typing_fill)
public val SparkIcons.TypingOutline: Resource get() = Resource(Res.drawable.spark_icons_typing_outline)
public val SparkIcons.Undo: Resource get() = Resource(Res.drawable.spark_icons_undo)
public val SparkIcons.Univers: Resource get() = Resource(Res.drawable.spark_icons_univers)
public val SparkIcons.UnlockFill: Resource get() = Resource(Res.drawable.spark_icons_unlock_fill)
public val SparkIcons.UnlockOutline: Resource get() = Resource(Res.drawable.spark_icons_unlock_outline)
public val SparkIcons.UrgentFill: Resource get() = Resource(Res.drawable.spark_icons_urgent_fill)
public val SparkIcons.UrgentOutline: Resource get() = Resource(Res.drawable.spark_icons_urgent_outline)
public val SparkIcons.UserCheckFill: Resource get() = Resource(Res.drawable.spark_icons_user_check_fill)
public val SparkIcons.UserCheckOutline: Resource get() = Resource(Res.drawable.spark_icons_user_check_outline)
public val SparkIcons.Vaccine: Resource get() = Resource(Res.drawable.spark_icons_vaccine)
public val SparkIcons.ValidFill: Resource get() = Resource(Res.drawable.spark_icons_valid_fill)
public val SparkIcons.ValidOutline: Resource get() = Resource(Res.drawable.spark_icons_valid_outline)
public val SparkIcons.VehicleWeight: Resource get() = Resource(Res.drawable.spark_icons_vehicle_weight)
public val SparkIcons.Vehicles: Resource get() = Resource(Res.drawable.spark_icons_vehicles)
public val SparkIcons.VerifiedFill: Resource get() = Resource(Res.drawable.spark_icons_verified_fill)
public val SparkIcons.VerifiedOutline: Resource get() = Resource(Res.drawable.spark_icons_verified_outline)
public val SparkIcons.View: Resource get() = Resource(Res.drawable.spark_icons_view)
public val SparkIcons.VoiceFill: Resource get() = Resource(Res.drawable.spark_icons_voice_fill)
public val SparkIcons.VoiceOffFill: Resource get() = Resource(Res.drawable.spark_icons_voice_off_fill)
public val SparkIcons.VoiceOffOutline: Resource get() = Resource(Res.drawable.spark_icons_voice_off_outline)
public val SparkIcons.VoiceOutline: Resource get() = Resource(Res.drawable.spark_icons_voice_outline)
public val SparkIcons.WalkerFill: Resource get() = Resource(Res.drawable.spark_icons_walker_fill)
public val SparkIcons.WalkerOutline: Resource get() = Resource(Res.drawable.spark_icons_walker_outline)
public val SparkIcons.Wallet: Resource get() = Resource(Res.drawable.spark_icons_wallet)
public val SparkIcons.Wardrobe: Resource get() = Resource(Res.drawable.spark_icons_wardrobe)
public val SparkIcons.WarningFill: Resource get() = Resource(Res.drawable.spark_icons_warning_fill)
public val SparkIcons.WarningOutline: Resource get() = Resource(Res.drawable.spark_icons_warning_outline)
public val SparkIcons.WarningSecurityFill: Resource get() = Resource(Res.drawable.spark_icons_warning_security_fill)
public val SparkIcons.WarningSecurityOutline: Resource
    get() =
        Resource(Res.drawable.spark_icons_warning_security_outline)
public val SparkIcons.Wc: Resource get() = Resource(Res.drawable.spark_icons_wc)
public val SparkIcons.Weight: Resource get() = Resource(Res.drawable.spark_icons_weight)
public val SparkIcons.Welcome: Resource get() = Resource(Res.drawable.spark_icons_welcome)
public val SparkIcons.Whatsapp: Resource get() = Resource(Res.drawable.spark_icons_whatsapp)
public val SparkIcons.WheelFill: Resource get() = Resource(Res.drawable.spark_icons_wheel_fill)
public val SparkIcons.WheelOutline: Resource get() = Resource(Res.drawable.spark_icons_wheel_outline)
public val SparkIcons.WheelRim: Resource get() = Resource(Res.drawable.spark_icons_wheel_rim)
public val SparkIcons.Wifi: Resource get() = Resource(Res.drawable.spark_icons_wifi)
public val SparkIcons.WorkFill: Resource get() = Resource(Res.drawable.spark_icons_work_fill)
public val SparkIcons.WorkOutline: Resource get() = Resource(Res.drawable.spark_icons_work_outline)
public val SparkIcons.Years: Resource get() = Resource(Res.drawable.spark_icons_years)
