name: '🐘 Setup Gradle'
description: 'Gradle setup and wrapper validation'
runs:
  using: composite
  steps:
    - uses: gradle/actions/setup-gradle@8379f6a1328ee0e06e2bb424dadb7b159856a326 # v4.4.0
      with:
        add-job-summary-as-pr-comment: on-failure
