name: '🐘 Setup Gradle'
description: 'Gradle setup and wrapper validation'
runs:
  using: composite
  steps:
    - uses: gradle/actions/setup-gradle@06832c7b30a0129d7fb559bcc6e43d26f6374244 # v4.3.1
      with:
        add-job-summary-as-pr-comment: on-failure
