/*
 * Copyright (c) 2023-2026 Adevinta
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
@file:Suppress("UnusedReceiverParameter", "unused", "ktlint", "DEPRECATION")

package com.adevinta.spark.icons

import com.adevinta.spark.icons.SparkIcon.DrawableRes

/**
 * A collection of static icons from Spark.
 *
 * This object provides access to all static vector icons as drawable resources.
 * Each icon is available as a property that returns a [SparkIcon.DrawableRes] or a [SparkIcon.Vector],
 * ensuring type safety and consistency across the icon system.
 *
 * @see SparkIcon.DrawableRes
 * @see SparkIcon.Vector
 */
@Deprecated("Use Leboncoin icons instead")
public object SparkIcons

@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Accessories: DrawableRes get() = DrawableRes(R.drawable.spark_icons_accessories)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.AccountFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_account_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.AccountOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_account_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Activity: DrawableRes get() = DrawableRes(R.drawable.spark_icons_activity)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.AddFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_add_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.AddImageFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_add_image_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.AddImageOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_add_image_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.AddOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_add_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.AddSquareFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_add_square_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.AddSquareOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_add_square_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Age: DrawableRes get() = DrawableRes(R.drawable.spark_icons_age)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.AirConditioning: DrawableRes get() = DrawableRes(R.drawable.spark_icons_air_conditioning)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.AlarmFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_alarm_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.AlarmOffFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_alarm_off_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.AlarmOffOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_alarm_off_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.AlarmOnFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_alarm_on_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.AlarmOnOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_alarm_on_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.AlarmOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_alarm_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.AlertFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_alert_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.AlertOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_alert_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.AllDirection: DrawableRes get() = DrawableRes(R.drawable.spark_icons_all_direction)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Animals: DrawableRes get() = DrawableRes(R.drawable.spark_icons_animals)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Apartment: DrawableRes get() = DrawableRes(R.drawable.spark_icons_apartment)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Appearance: DrawableRes get() = DrawableRes(R.drawable.spark_icons_appearance)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Arrival: DrawableRes get() = DrawableRes(R.drawable.spark_icons_arrival)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ArrowDoubleLeft: DrawableRes get() = DrawableRes(R.drawable.spark_icons_arrow_double_left)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ArrowDoubleRight: DrawableRes get() = DrawableRes(R.drawable.spark_icons_arrow_double_right)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ArrowHorizontalDown: DrawableRes get() = DrawableRes(R.drawable.spark_icons_arrow_horizontal_down)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ArrowHorizontalUp: DrawableRes get() = DrawableRes(R.drawable.spark_icons_arrow_horizontal_up)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ArrowLeft: DrawableRes get() = DrawableRes(R.drawable.spark_icons_arrow_left)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ArrowRight: DrawableRes get() = DrawableRes(R.drawable.spark_icons_arrow_right)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ArrowVerticalLeft: DrawableRes get() = DrawableRes(R.drawable.spark_icons_arrow_vertical_left)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ArrowVerticalRight: DrawableRes get() = DrawableRes(R.drawable.spark_icons_arrow_vertical_right)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.AttachFile: DrawableRes get() = DrawableRes(R.drawable.spark_icons_attach_file)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Attic: DrawableRes get() = DrawableRes(R.drawable.spark_icons_attic)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Available: DrawableRes get() = DrawableRes(R.drawable.spark_icons_available)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Axles: DrawableRes get() = DrawableRes(R.drawable.spark_icons_axles)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Baby: DrawableRes get() = DrawableRes(R.drawable.spark_icons_baby)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.BabyFurniture: DrawableRes get() = DrawableRes(R.drawable.spark_icons_baby_furniture)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Balcony: DrawableRes get() = DrawableRes(R.drawable.spark_icons_balcony)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.BankFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_bank_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.BankOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_bank_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Basement: DrawableRes get() = DrawableRes(R.drawable.spark_icons_basement)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.BatchPurchase: DrawableRes get() = DrawableRes(R.drawable.spark_icons_batch_purchase)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Bath: DrawableRes get() = DrawableRes(R.drawable.spark_icons_bath)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.BeautifulBuilding: DrawableRes get() = DrawableRes(R.drawable.spark_icons_beautiful_building)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.BicycleType: DrawableRes get() = DrawableRes(R.drawable.spark_icons_bicycle_type)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Bike: DrawableRes get() = DrawableRes(R.drawable.spark_icons_bike)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.BikeSize: DrawableRes get() = DrawableRes(R.drawable.spark_icons_bike_size)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Block: DrawableRes get() = DrawableRes(R.drawable.spark_icons_block)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Bluetooth: DrawableRes get() = DrawableRes(R.drawable.spark_icons_bluetooth)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Boat: DrawableRes get() = DrawableRes(R.drawable.spark_icons_boat)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Book: DrawableRes get() = DrawableRes(R.drawable.spark_icons_book)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.BookmarkFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_bookmark_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.BookmarkOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_bookmark_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Booster: DrawableRes get() = DrawableRes(R.drawable.spark_icons_booster)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.BoxFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_box_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.BoxOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_box_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Brand: DrawableRes get() = DrawableRes(R.drawable.spark_icons_brand)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Breakfast: DrawableRes get() = DrawableRes(R.drawable.spark_icons_breakfast)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Bump: DrawableRes get() = DrawableRes(R.drawable.spark_icons_bump)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.BurgerMenu: DrawableRes get() = DrawableRes(R.drawable.spark_icons_burger_menu)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.CalculateFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_calculate_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.CalculateOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_calculate_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.CalendarCriterias: DrawableRes get() = DrawableRes(R.drawable.spark_icons_calendar_criterias)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.CalendarDotFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_calendar_dot_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.CalendarDotOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_calendar_dot_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.CalendarFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_calendar_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.CalendarOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_calendar_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.CalendarValidFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_calendar_valid_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.CalendarValidOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_calendar_valid_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.CallEnterFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_call_enter_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.CallEnterOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_call_enter_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.CallFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_call_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.CallMissFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_call_miss_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.CallMissOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_call_miss_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.CallOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_call_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Calm: DrawableRes get() = DrawableRes(R.drawable.spark_icons_calm)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.CameraFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_camera_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.CameraOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_camera_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.CameraVideo: DrawableRes get() = DrawableRes(R.drawable.spark_icons_camera_video)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Capacity: DrawableRes get() = DrawableRes(R.drawable.spark_icons_capacity)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.CarBrand: DrawableRes get() = DrawableRes(R.drawable.spark_icons_car_brand)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.CarFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_car_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.CarOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_car_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.CarType: DrawableRes get() = DrawableRes(R.drawable.spark_icons_car_type)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.CarWarrantyFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_car_warranty_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.CarWarrantyOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_car_warranty_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Card: DrawableRes get() = DrawableRes(R.drawable.spark_icons_card)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.CardFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_card_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.CardOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_card_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.CategoriesClothes: DrawableRes get() = DrawableRes(R.drawable.spark_icons_categories_clothes)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Cave: DrawableRes get() = DrawableRes(R.drawable.spark_icons_cave)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ChargesIncluded: DrawableRes get() = DrawableRes(R.drawable.spark_icons_charges_included)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Check: DrawableRes get() = DrawableRes(R.drawable.spark_icons_check)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Class: DrawableRes get() = DrawableRes(R.drawable.spark_icons_class)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Clean: DrawableRes get() = DrawableRes(R.drawable.spark_icons_clean)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ClockArrow: DrawableRes get() = DrawableRes(R.drawable.spark_icons_clock_arrow)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ClockFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_clock_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ClockOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_clock_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Close: DrawableRes get() = DrawableRes(R.drawable.spark_icons_close)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Clothes: DrawableRes get() = DrawableRes(R.drawable.spark_icons_clothes)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ClothesBrand: DrawableRes get() = DrawableRes(R.drawable.spark_icons_clothes_brand)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ClothesCondition: DrawableRes get() = DrawableRes(R.drawable.spark_icons_clothes_condition)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Collectible: DrawableRes get() = DrawableRes(R.drawable.spark_icons_collectible)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Color: DrawableRes get() = DrawableRes(R.drawable.spark_icons_color)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Common: DrawableRes get() = DrawableRes(R.drawable.spark_icons_common)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Computer: DrawableRes get() = DrawableRes(R.drawable.spark_icons_computer)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ComputerAccessory: DrawableRes get() = DrawableRes(R.drawable.spark_icons_computer_accessory)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Condition: DrawableRes get() = DrawableRes(R.drawable.spark_icons_condition)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ConversationFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_conversation_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ConversationOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_conversation_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.CopyFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_copy_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.CopyOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_copy_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Couch: DrawableRes get() = DrawableRes(R.drawable.spark_icons_couch)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.CountryFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_country_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.CountryOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_country_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Crop: DrawableRes get() = DrawableRes(R.drawable.spark_icons_crop)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.CvFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_cv_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.CvOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_cv_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Cylindrical: DrawableRes get() = DrawableRes(R.drawable.spark_icons_cylindrical)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.DarkMode: DrawableRes get() = DrawableRes(R.drawable.spark_icons_dark_mode)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.DeleteFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_delete_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.DeleteOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_delete_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Delivery: DrawableRes get() = DrawableRes(R.drawable.spark_icons_delivery)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.DeliveryFastFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_delivery_fast_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.DeliveryFastOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_delivery_fast_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.DeliveryFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_delivery_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.DeliveryHandsFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_delivery_hands_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.DeliveryHandsOutline: DrawableRes
    get() =
        DrawableRes(R.drawable.spark_icons_delivery_hands_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.DeliveryOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_delivery_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.DeliveryTruckFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_delivery_truck_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.DeliveryTruckOutline: DrawableRes
    get() =
        DrawableRes(R.drawable.spark_icons_delivery_truck_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Digicode: DrawableRes get() = DrawableRes(R.drawable.spark_icons_digicode)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Directory: DrawableRes get() = DrawableRes(R.drawable.spark_icons_directory)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.DissatisfiedFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_dissatisfied_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.DissatisfiedOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_dissatisfied_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.DiyProduct: DrawableRes get() = DrawableRes(R.drawable.spark_icons_diy_product)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.DiyType: DrawableRes get() = DrawableRes(R.drawable.spark_icons_diy_type)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Donate: DrawableRes get() = DrawableRes(R.drawable.spark_icons_donate)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Donation: DrawableRes get() = DrawableRes(R.drawable.spark_icons_donation)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Doors: DrawableRes get() = DrawableRes(R.drawable.spark_icons_doors)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.DoubleCheck: DrawableRes get() = DrawableRes(R.drawable.spark_icons_double_check)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.DownloadFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_download_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.DownloadOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_download_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Dress: DrawableRes get() = DrawableRes(R.drawable.spark_icons_dress)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.DumpTruck: DrawableRes get() = DrawableRes(R.drawable.spark_icons_dump_truck)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Duplex: DrawableRes get() = DrawableRes(R.drawable.spark_icons_duplex)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.EducationalLevel: DrawableRes get() = DrawableRes(R.drawable.spark_icons_educational_level)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Energy: DrawableRes get() = DrawableRes(R.drawable.spark_icons_energy)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.EngineStart: DrawableRes get() = DrawableRes(R.drawable.spark_icons_engine_start)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Equipment: DrawableRes get() = DrawableRes(R.drawable.spark_icons_equipment)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.EquipmentBaby: DrawableRes get() = DrawableRes(R.drawable.spark_icons_equipment_baby)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ErrorPhoto: DrawableRes get() = DrawableRes(R.drawable.spark_icons_error_photo)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Euro: DrawableRes get() = DrawableRes(R.drawable.spark_icons_euro)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Experience: DrawableRes get() = DrawableRes(R.drawable.spark_icons_experience)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Export: DrawableRes get() = DrawableRes(R.drawable.spark_icons_export)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.EyeFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_eye_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.EyeOffFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_eye_off_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.EyeOffOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_eye_off_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.EyeOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_eye_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.FacebookFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_facebook_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.FacebookOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_facebook_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Family: DrawableRes get() = DrawableRes(R.drawable.spark_icons_family)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.FavoriteFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_favorite_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.FavoriteOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_favorite_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.FeedbackFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_feedback_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.FeedbackOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_feedback_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.FileOffFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_file_off_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.FileOffOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_file_off_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.FilePdfFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_file_pdf_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.FilePdfOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_file_pdf_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Filter: DrawableRes get() = DrawableRes(R.drawable.spark_icons_filter)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.FireFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_fire_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.FireOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_fire_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Fireplace: DrawableRes get() = DrawableRes(R.drawable.spark_icons_fireplace)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.FlagFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_flag_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.FlagOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_flag_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.FlashFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_flash_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.FlashOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_flash_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.FlashlightFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_flashlight_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.FlashlightOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_flashlight_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Floor: DrawableRes get() = DrawableRes(R.drawable.spark_icons_floor)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ForwardFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_forward_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ForwardOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_forward_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Fuel: DrawableRes get() = DrawableRes(R.drawable.spark_icons_fuel)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Function: DrawableRes get() = DrawableRes(R.drawable.spark_icons_function)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Furniture: DrawableRes get() = DrawableRes(R.drawable.spark_icons_furniture)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.FurnitureType: DrawableRes get() = DrawableRes(R.drawable.spark_icons_furniture_type)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.GalleryFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_gallery_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.GalleryOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_gallery_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Garage: DrawableRes get() = DrawableRes(R.drawable.spark_icons_garage)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Garden: DrawableRes get() = DrawableRes(R.drawable.spark_icons_garden)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.GardeningProduct: DrawableRes get() = DrawableRes(R.drawable.spark_icons_gardening_product)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.GardeningType: DrawableRes get() = DrawableRes(R.drawable.spark_icons_gardening_type)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.GlassWindows: DrawableRes get() = DrawableRes(R.drawable.spark_icons_glass_windows)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Gps: DrawableRes get() = DrawableRes(R.drawable.spark_icons_gps)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.GraphArrowDown: DrawableRes get() = DrawableRes(R.drawable.spark_icons_graph_arrow_down)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.GraphArrowUp: DrawableRes get() = DrawableRes(R.drawable.spark_icons_graph_arrow_up)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.GraphFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_graph_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.GraphOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_graph_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Ground: DrawableRes get() = DrawableRes(R.drawable.spark_icons_ground)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.GroupFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_group_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.GroupOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_group_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.HandDelivered: DrawableRes get() = DrawableRes(R.drawable.spark_icons_hand_delivered)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Headlight: DrawableRes get() = DrawableRes(R.drawable.spark_icons_headlight)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Highlight: DrawableRes get() = DrawableRes(R.drawable.spark_icons_highlight)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Hobby: DrawableRes get() = DrawableRes(R.drawable.spark_icons_hobby)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.HolidayFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_holiday_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.HolidayOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_holiday_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Holidays: DrawableRes get() = DrawableRes(R.drawable.spark_icons_holidays)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.HolidaysGarden: DrawableRes get() = DrawableRes(R.drawable.spark_icons_holidays_garden)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.HomeFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_home_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.HomeOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_home_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.HomeappliancesProduct: DrawableRes
    get() =
        DrawableRes(R.drawable.spark_icons_homeappliances_product)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.HomeappliancesType: DrawableRes
    get() =
        DrawableRes(R.drawable.spark_icons_homeappliances_type)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Honoraria: DrawableRes get() = DrawableRes(R.drawable.spark_icons_honoraria)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.HotelFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_hotel_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.HotelOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_hotel_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.House: DrawableRes get() = DrawableRes(R.drawable.spark_icons_house)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.HousingType: DrawableRes get() = DrawableRes(R.drawable.spark_icons_housing_type)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.IdeaFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_idea_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.IdeaOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_idea_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.IdentityFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_identity_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.IdentityOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_identity_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ImageFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_image_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ImageOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_image_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Import: DrawableRes get() = DrawableRes(R.drawable.spark_icons_import)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.InfoFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_info_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.InfoOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_info_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.InstagramFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_instagram_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.InstagramOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_instagram_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Interphone: DrawableRes get() = DrawableRes(R.drawable.spark_icons_interphone)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Janitor: DrawableRes get() = DrawableRes(R.drawable.spark_icons_janitor)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Jewels: DrawableRes get() = DrawableRes(R.drawable.spark_icons_jewels)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Job: DrawableRes get() = DrawableRes(R.drawable.spark_icons_job)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.JobType: DrawableRes get() = DrawableRes(R.drawable.spark_icons_job_type)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.KeyFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_key_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.KeyOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_key_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.KeylessAccess: DrawableRes get() = DrawableRes(R.drawable.spark_icons_keyless_access)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Land: DrawableRes get() = DrawableRes(R.drawable.spark_icons_land)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.LastFloor: DrawableRes get() = DrawableRes(R.drawable.spark_icons_last_floor)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Lens: DrawableRes get() = DrawableRes(R.drawable.spark_icons_lens)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.License: DrawableRes get() = DrawableRes(R.drawable.spark_icons_license)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Lift: DrawableRes get() = DrawableRes(R.drawable.spark_icons_lift)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Light: DrawableRes get() = DrawableRes(R.drawable.spark_icons_light)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.LightMode: DrawableRes get() = DrawableRes(R.drawable.spark_icons_light_mode)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Like: DrawableRes get() = DrawableRes(R.drawable.spark_icons_like)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.LikeFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_like_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.LikeOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_like_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.LinensProduct: DrawableRes get() = DrawableRes(R.drawable.spark_icons_linens_product)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.LinensType: DrawableRes get() = DrawableRes(R.drawable.spark_icons_linens_type)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Link: DrawableRes get() = DrawableRes(R.drawable.spark_icons_link)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Linkedin: DrawableRes get() = DrawableRes(R.drawable.spark_icons_linkedin)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Listing: DrawableRes get() = DrawableRes(R.drawable.spark_icons_listing)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Litter: DrawableRes get() = DrawableRes(R.drawable.spark_icons_litter)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Loader: DrawableRes get() = DrawableRes(R.drawable.spark_icons_loader)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Localisation: DrawableRes get() = DrawableRes(R.drawable.spark_icons_localisation)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.LockFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_lock_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.LockOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_lock_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Loft: DrawableRes get() = DrawableRes(R.drawable.spark_icons_loft)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Loggia: DrawableRes get() = DrawableRes(R.drawable.spark_icons_loggia)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Loof: DrawableRes get() = DrawableRes(R.drawable.spark_icons_loof)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Luxe: DrawableRes get() = DrawableRes(R.drawable.spark_icons_luxe)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.MailCloseFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_mail_close_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.MailCloseOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_mail_close_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.MailFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_mail_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.MailOpenFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_mail_open_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.MailOpenOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_mail_open_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.MailOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_mail_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.MapCursorFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_map_cursor_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.MapCursorOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_map_cursor_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.MapExpand: DrawableRes get() = DrawableRes(R.drawable.spark_icons_map_expand)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Material: DrawableRes get() = DrawableRes(R.drawable.spark_icons_material)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.MegaphoneFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_megaphone_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.MegaphoneMuteFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_megaphone_mute_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.MegaphoneMuteOutline: DrawableRes
    get() =
        DrawableRes(R.drawable.spark_icons_megaphone_mute_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.MegaphoneOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_megaphone_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Memory: DrawableRes get() = DrawableRes(R.drawable.spark_icons_memory)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.MessageFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_message_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.MessageOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_message_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Messenger: DrawableRes get() = DrawableRes(R.drawable.spark_icons_messenger)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Metro: DrawableRes get() = DrawableRes(R.drawable.spark_icons_metro)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Mileage: DrawableRes get() = DrawableRes(R.drawable.spark_icons_mileage)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Minus: DrawableRes get() = DrawableRes(R.drawable.spark_icons_minus)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.MobileCheck: DrawableRes get() = DrawableRes(R.drawable.spark_icons_mobile_check)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Model: DrawableRes get() = DrawableRes(R.drawable.spark_icons_model)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.MoneyFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_money_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.MoneyOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_money_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.MoreMenuHorizontal: DrawableRes get() = DrawableRes(R.drawable.spark_icons_more_menu_horizontal)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.MoreMenuVertical: DrawableRes get() = DrawableRes(R.drawable.spark_icons_more_menu_vertical)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Moto: DrawableRes get() = DrawableRes(R.drawable.spark_icons_moto)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Moulding: DrawableRes get() = DrawableRes(R.drawable.spark_icons_moulding)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.MoveUp: DrawableRes get() = DrawableRes(R.drawable.spark_icons_move_up)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Multimedia: DrawableRes get() = DrawableRes(R.drawable.spark_icons_multimedia)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.MultimediaSystem: DrawableRes get() = DrawableRes(R.drawable.spark_icons_multimedia_system)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.NeutralFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_neutral_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.NeutralOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_neutral_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.NoPhoto: DrawableRes get() = DrawableRes(R.drawable.spark_icons_no_photo)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.NotificationFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_notification_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.NotificationOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_notification_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Offer: DrawableRes get() = DrawableRes(R.drawable.spark_icons_offer)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.OfferFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_offer_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.OfferOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_offer_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.OfferType: DrawableRes get() = DrawableRes(R.drawable.spark_icons_offer_type)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.PaperMapFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_paper_map_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.PaperMapOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_paper_map_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ParkAssist: DrawableRes get() = DrawableRes(R.drawable.spark_icons_park_assist)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Parking: DrawableRes get() = DrawableRes(R.drawable.spark_icons_parking)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ParkingEstate: DrawableRes get() = DrawableRes(R.drawable.spark_icons_parking_estate)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ParkingSensor: DrawableRes get() = DrawableRes(R.drawable.spark_icons_parking_sensor)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Parquet: DrawableRes get() = DrawableRes(R.drawable.spark_icons_parquet)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.PauseFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_pause_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.PauseOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_pause_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.PenFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_pen_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.PenOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_pen_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Percentage: DrawableRes get() = DrawableRes(R.drawable.spark_icons_percentage)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.PetAccessory: DrawableRes get() = DrawableRes(R.drawable.spark_icons_pet_accessory)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Pets: DrawableRes get() = DrawableRes(R.drawable.spark_icons_pets)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.PhoneFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_phone_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.PhoneOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_phone_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.PhotoPack: DrawableRes get() = DrawableRes(R.drawable.spark_icons_photo_pack)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Pieces: DrawableRes get() = DrawableRes(R.drawable.spark_icons_pieces)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.PiggyBankFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_piggy_bank_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.PiggyBankOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_piggy_bank_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.PinFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_pin_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.PinOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_pin_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Pinterest: DrawableRes get() = DrawableRes(R.drawable.spark_icons_pinterest)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.PlayFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_play_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.PlayOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_play_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Plus: DrawableRes get() = DrawableRes(R.drawable.spark_icons_plus)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Pool: DrawableRes get() = DrawableRes(R.drawable.spark_icons_pool)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Power: DrawableRes get() = DrawableRes(R.drawable.spark_icons_power)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.PrintFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_print_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.PrintOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_print_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ProCursorFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_pro_cursor_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ProCursorOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_pro_cursor_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ProFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_pro_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ProOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_pro_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ProfileFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_profile_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ProfileOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_profile_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.QuestionFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_question_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.QuestionOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_question_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.RainSensor: DrawableRes get() = DrawableRes(R.drawable.spark_icons_rain_sensor)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Rating: DrawableRes get() = DrawableRes(R.drawable.spark_icons_rating)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.RearviewCamera: DrawableRes get() = DrawableRes(R.drawable.spark_icons_rearview_camera)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.RearviewMirror: DrawableRes get() = DrawableRes(R.drawable.spark_icons_rearview_mirror)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Redo: DrawableRes get() = DrawableRes(R.drawable.spark_icons_redo)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Reference: DrawableRes get() = DrawableRes(R.drawable.spark_icons_reference)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Refresh: DrawableRes get() = DrawableRes(R.drawable.spark_icons_refresh)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Refund: DrawableRes get() = DrawableRes(R.drawable.spark_icons_refund)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.RemoveFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_remove_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.RemoveOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_remove_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Renovation: DrawableRes get() = DrawableRes(R.drawable.spark_icons_renovation)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Rental: DrawableRes get() = DrawableRes(R.drawable.spark_icons_rental)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.RocketFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_rocket_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.RocketOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_rocket_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Rooms: DrawableRes get() = DrawableRes(R.drawable.spark_icons_rooms)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.RotateImage: DrawableRes get() = DrawableRes(R.drawable.spark_icons_rotate_image)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.SadFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_sad_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.SadOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_sad_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Salary: DrawableRes get() = DrawableRes(R.drawable.spark_icons_salary)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.SaleType: DrawableRes get() = DrawableRes(R.drawable.spark_icons_sale_type)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.SatisfiedFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_satisfied_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.SatisfiedOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_satisfied_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Scan: DrawableRes get() = DrawableRes(R.drawable.spark_icons_scan)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.SeaView: DrawableRes get() = DrawableRes(R.drawable.spark_icons_sea_view)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Search: DrawableRes get() = DrawableRes(R.drawable.spark_icons_search)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.SearchFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_search_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.SearchOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_search_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Seat: DrawableRes get() = DrawableRes(R.drawable.spark_icons_seat)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Seats: DrawableRes get() = DrawableRes(R.drawable.spark_icons_seats)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Sector: DrawableRes get() = DrawableRes(R.drawable.spark_icons_sector)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.SecurityFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_security_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.SecurityOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_security_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.SecurityProfileAccountFill: DrawableRes
    get() =
        DrawableRes(R.drawable.spark_icons_security_profile_account_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.SecurityProfileAccountOutline: DrawableRes
    get() =
        DrawableRes(R.drawable.spark_icons_security_profile_account_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.SecurityProfileFill: DrawableRes
    get() =
        DrawableRes(R.drawable.spark_icons_security_profile_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.SecurityProfileOutline: DrawableRes
    get() =
        DrawableRes(R.drawable.spark_icons_security_profile_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Seller: DrawableRes get() = DrawableRes(R.drawable.spark_icons_seller)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.SendFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_send_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.SendHorizontal: DrawableRes get() = DrawableRes(R.drawable.spark_icons_send_horizontal)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.SendOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_send_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Service: DrawableRes get() = DrawableRes(R.drawable.spark_icons_service)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ShareExpand: DrawableRes get() = DrawableRes(R.drawable.spark_icons_share_expand)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ShareFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_share_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ShareOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_share_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ShareiOS: DrawableRes get() = DrawableRes(R.drawable.spark_icons_sharei_o_s)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ShoeSize: DrawableRes get() = DrawableRes(R.drawable.spark_icons_shoe_size)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Shoes: DrawableRes get() = DrawableRes(R.drawable.spark_icons_shoes)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ShoppingCartFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_shopping_cart_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ShoppingCartOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_shopping_cart_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ShovelRake: DrawableRes get() = DrawableRes(R.drawable.spark_icons_shovel_rake)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Shower: DrawableRes get() = DrawableRes(R.drawable.spark_icons_shower)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Size: DrawableRes get() = DrawableRes(R.drawable.spark_icons_size)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Smoking: DrawableRes get() = DrawableRes(R.drawable.spark_icons_smoking)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Sort: DrawableRes get() = DrawableRes(R.drawable.spark_icons_sort)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.SortFilled: DrawableRes get() = DrawableRes(R.drawable.spark_icons_sort_filled)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Spa: DrawableRes get() = DrawableRes(R.drawable.spark_icons_spa)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Speaker: DrawableRes get() = DrawableRes(R.drawable.spark_icons_speaker)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Speed: DrawableRes get() = DrawableRes(R.drawable.spark_icons_speed)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.SpeedIndicator: DrawableRes get() = DrawableRes(R.drawable.spark_icons_speed_indicator)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.SpeedmeterFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_speedmeter_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.SpeedmeterOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_speedmeter_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Sport: DrawableRes get() = DrawableRes(R.drawable.spark_icons_sport)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.StarFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_star_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.StarOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_star_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Start: DrawableRes get() = DrawableRes(R.drawable.spark_icons_start)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Store: DrawableRes get() = DrawableRes(R.drawable.spark_icons_store)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.StoreFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_store_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.StoreOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_store_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Sun: DrawableRes get() = DrawableRes(R.drawable.spark_icons_sun)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.SunOrientation: DrawableRes get() = DrawableRes(R.drawable.spark_icons_sun_orientation)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Sunroof: DrawableRes get() = DrawableRes(R.drawable.spark_icons_sunroof)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.SupportFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_support_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.SupportOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_support_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.SupportSmileFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_support_smile_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.SupportSmileOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_support_smile_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Surface: DrawableRes get() = DrawableRes(R.drawable.spark_icons_surface)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.TableArtMaterial: DrawableRes get() = DrawableRes(R.drawable.spark_icons_table_art_material)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.TableArtProduct: DrawableRes get() = DrawableRes(R.drawable.spark_icons_table_art_product)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.TargetFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_target_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.TargetOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_target_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Tattoo: DrawableRes get() = DrawableRes(R.drawable.spark_icons_tattoo)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Terrace: DrawableRes get() = DrawableRes(R.drawable.spark_icons_terrace)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ThreeD: DrawableRes get() = DrawableRes(R.drawable.spark_icons_three_d)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ThreeSixty: DrawableRes get() = DrawableRes(R.drawable.spark_icons_three_sixty)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Time: DrawableRes get() = DrawableRes(R.drawable.spark_icons_time)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Tools: DrawableRes get() = DrawableRes(R.drawable.spark_icons_tools)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.TopAd: DrawableRes get() = DrawableRes(R.drawable.spark_icons_top_ad)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Toy: DrawableRes get() = DrawableRes(R.drawable.spark_icons_toy)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ToysProduct: DrawableRes get() = DrawableRes(R.drawable.spark_icons_toys_product)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Tractor: DrawableRes get() = DrawableRes(R.drawable.spark_icons_tractor)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.TrainFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_train_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.TrainOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_train_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.TrashCloseFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_trash_close_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.TrashCloseOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_trash_close_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.TrashFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_trash_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.TrashOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_trash_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Truck: DrawableRes get() = DrawableRes(R.drawable.spark_icons_truck)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Trunk: DrawableRes get() = DrawableRes(R.drawable.spark_icons_trunk)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Tv: DrawableRes get() = DrawableRes(R.drawable.spark_icons_tv)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Twitter: DrawableRes get() = DrawableRes(R.drawable.spark_icons_twitter)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Type: DrawableRes get() = DrawableRes(R.drawable.spark_icons_type)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.TypingFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_typing_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.TypingOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_typing_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Undo: DrawableRes get() = DrawableRes(R.drawable.spark_icons_undo)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Univers: DrawableRes get() = DrawableRes(R.drawable.spark_icons_univers)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.UnlockFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_unlock_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.UnlockOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_unlock_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.UrgentFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_urgent_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.UrgentOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_urgent_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.UserCheckFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_user_check_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.UserCheckOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_user_check_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Vaccine: DrawableRes get() = DrawableRes(R.drawable.spark_icons_vaccine)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ValidFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_valid_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.ValidOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_valid_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.VehicleWeight: DrawableRes get() = DrawableRes(R.drawable.spark_icons_vehicle_weight)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Vehicles: DrawableRes get() = DrawableRes(R.drawable.spark_icons_vehicles)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.VerifiedFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_verified_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.VerifiedOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_verified_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.View: DrawableRes get() = DrawableRes(R.drawable.spark_icons_view)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.VoiceFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_voice_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.VoiceOffFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_voice_off_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.VoiceOffOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_voice_off_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.VoiceOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_voice_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.WalkerFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_walker_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.WalkerOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_walker_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Wallet: DrawableRes get() = DrawableRes(R.drawable.spark_icons_wallet)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Wardrobe: DrawableRes get() = DrawableRes(R.drawable.spark_icons_wardrobe)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.WarningFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_warning_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.WarningOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_warning_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.WarningSecurityFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_warning_security_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.WarningSecurityOutline: DrawableRes
    get() =
        DrawableRes(R.drawable.spark_icons_warning_security_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Wc: DrawableRes get() = DrawableRes(R.drawable.spark_icons_wc)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Weight: DrawableRes get() = DrawableRes(R.drawable.spark_icons_weight)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Welcome: DrawableRes get() = DrawableRes(R.drawable.spark_icons_welcome)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Whatsapp: DrawableRes get() = DrawableRes(R.drawable.spark_icons_whatsapp)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.WheelFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_wheel_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.WheelOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_wheel_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.WheelRim: DrawableRes get() = DrawableRes(R.drawable.spark_icons_wheel_rim)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Wifi: DrawableRes get() = DrawableRes(R.drawable.spark_icons_wifi)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.WorkFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_work_fill)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.WorkOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_work_outline)
@Deprecated("Use Leboncoin icons instead")
public val SparkIcons.Years: DrawableRes get() = DrawableRes(R.drawable.spark_icons_years)
