name: '🤖 Setup Kotlin'
description: 'Kotlin setup'

inputs:
  kotlin-version:
    description: 'Kotlin version'
    # Don't use 2.4.0 as it breaks our kotlin scripts, it should be fixed in 2.4.10. see KT-86352
    default: '2.3.21'
    required: true

runs:
  using: composite
  steps:
    - uses: actions/cache@v6
      id: cache
      with:
        path: ~/.kotlin
        key: kotlin-${{ inputs.kotlin-version }}-${{ runner.os }}

    - name: 'Installing Kotlin v${{ inputs.kotlin-version }}'
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir --parents ~/.kotlin
        wget --https-only --no-verbose -O "$KOTLIN_ZIP" "$KOTLIN_URL"
        unzip "$KOTLIN_ZIP" -d ~/.kotlin
      env:
        KOTLIN_URL: https://github.com/JetBrains/kotlin/releases/download/v${{ inputs.kotlin-version }}/kotlin-compiler-${{ inputs.kotlin-version }}.zip
        KOTLIN_ZIP: ${{ runner.temp }}/kotlin-${{ inputs.kotlin-version }}.zip

    - name: 'Add Kotlin to PATH'
      shell: bash
      # zizmor: ignore[github-env] -- path is hardcoded, no external input reaches it
      run: echo "$HOME/.kotlin/kotlinc/bin" >> $GITHUB_PATH
