/*
 * Copyright (c) 2023 Adevinta
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
@file:Suppress("UnusedReceiverParameter", "unused", "ktlint")

package com.adevinta.spark.icons

import com.adevinta.spark.icons.SparkIcon.DrawableRes

public object SparkIcons

public val SparkIcons.Activity: DrawableRes get() = DrawableRes(R.drawable.spark_icons_activity)
public val SparkIcons.AddImageFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_add_image_fill)
public val SparkIcons.AddImageOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_add_image_outline)
public val SparkIcons.AddSquareFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_add_square_fill)
public val SparkIcons.AddSquareOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_add_square_outline)
public val SparkIcons.AlertFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_alert_fill)
public val SparkIcons.AlertOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_alert_outline)
public val SparkIcons.ArrowLeft: DrawableRes get() = DrawableRes(R.drawable.spark_icons_arrow_left)
public val SparkIcons.ArrowRight: DrawableRes get() = DrawableRes(R.drawable.spark_icons_arrow_right)
public val SparkIcons.AttachFile: DrawableRes get() = DrawableRes(R.drawable.spark_icons_attach_file)
public val SparkIcons.Bike: DrawableRes get() = DrawableRes(R.drawable.spark_icons_bike)
public val SparkIcons.Book: DrawableRes get() = DrawableRes(R.drawable.spark_icons_book)
public val SparkIcons.BookmarkFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_bookmark_fill)
public val SparkIcons.BookmarkOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_bookmark_outline)
public val SparkIcons.BoxFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_box_fill)
public val SparkIcons.BoxOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_box_outline)
public val SparkIcons.BurgerMenu: DrawableRes get() = DrawableRes(R.drawable.spark_icons_burger_menu)
public val SparkIcons.CalendarDotFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_calendar_dot_fill)
public val SparkIcons.CalendarDotOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_calendar_dot_outline)
public val SparkIcons.CameraFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_camera_fill)
public val SparkIcons.CameraOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_camera_outline)
public val SparkIcons.CameraVideo: DrawableRes get() = DrawableRes(R.drawable.spark_icons_camera_video)
public val SparkIcons.CarFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_car_fill)
public val SparkIcons.CarOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_car_outline)
public val SparkIcons.CarWarrantyFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_car_warranty_fill)
public val SparkIcons.CarWarrantyOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_car_warranty_outline)
public val SparkIcons.Check: DrawableRes get() = DrawableRes(R.drawable.spark_icons_check)
public val SparkIcons.ClockArrow: DrawableRes get() = DrawableRes(R.drawable.spark_icons_clock_arrow)
public val SparkIcons.ClockFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_clock_fill)
public val SparkIcons.ClockOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_clock_outline)
public val SparkIcons.Computer: DrawableRes get() = DrawableRes(R.drawable.spark_icons_computer)
public val SparkIcons.CopyFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_copy_fill)
public val SparkIcons.CopyOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_copy_outline)
public val SparkIcons.Couch: DrawableRes get() = DrawableRes(R.drawable.spark_icons_couch)
public val SparkIcons.Crop: DrawableRes get() = DrawableRes(R.drawable.spark_icons_crop)
public val SparkIcons.DeliveryHandsFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_delivery_hands_fill)
public val SparkIcons.DeliveryHandsOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_delivery_hands_outline)
public val SparkIcons.DeliveryTruckFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_delivery_truck_fill)
public val SparkIcons.DeliveryTruckOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_delivery_truck_outline)
public val SparkIcons.DoubleCheck: DrawableRes get() = DrawableRes(R.drawable.spark_icons_double_check)
public val SparkIcons.Dress: DrawableRes get() = DrawableRes(R.drawable.spark_icons_dress)
public val SparkIcons.Export: DrawableRes get() = DrawableRes(R.drawable.spark_icons_export)
public val SparkIcons.EyeFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_eye_fill)
public val SparkIcons.EyeOffFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_eye_off_fill)
public val SparkIcons.EyeOffOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_eye_off_outline)
public val SparkIcons.EyeOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_eye_outline)
public val SparkIcons.Family: DrawableRes get() = DrawableRes(R.drawable.spark_icons_family)
public val SparkIcons.FileOffFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_file_off_fill)
public val SparkIcons.Filter: DrawableRes get() = DrawableRes(R.drawable.spark_icons_filter)
public val SparkIcons.FireFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_fire_fill)
public val SparkIcons.FireOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_fire_outline)
public val SparkIcons.FlagFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_flag_fill)
public val SparkIcons.FlagOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_flag_outline)
public val SparkIcons.FlashlightFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_flashlight_fill)
public val SparkIcons.FlashlightOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_flashlight_outline)
public val SparkIcons.ForwardFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_forward_fill)
public val SparkIcons.ForwardOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_forward_outline)
public val SparkIcons.GalleryFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_gallery_fill)
public val SparkIcons.GalleryOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_gallery_outline)
public val SparkIcons.Garage: DrawableRes get() = DrawableRes(R.drawable.spark_icons_garage)
public val SparkIcons.GraphArrowDown: DrawableRes get() = DrawableRes(R.drawable.spark_icons_graph_arrow_down)
public val SparkIcons.GraphArrowUp: DrawableRes get() = DrawableRes(R.drawable.spark_icons_graph_arrow_up)
public val SparkIcons.GraphFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_graph_fill)
public val SparkIcons.GraphOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_graph_outline)
public val SparkIcons.GroupFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_group_fill)
public val SparkIcons.GroupOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_group_outline)
public val SparkIcons.Highlight: DrawableRes get() = DrawableRes(R.drawable.spark_icons_highlight)
public val SparkIcons.HomeFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_home_fill)
public val SparkIcons.HomeOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_home_outline)
public val SparkIcons.House: DrawableRes get() = DrawableRes(R.drawable.spark_icons_house)
public val SparkIcons.ImageFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_image_fill)
public val SparkIcons.ImageOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_image_outline)
public val SparkIcons.Import: DrawableRes get() = DrawableRes(R.drawable.spark_icons_import)
public val SparkIcons.InfoFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_info_fill)
public val SparkIcons.InfoOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_info_outline)
public val SparkIcons.KeyFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_key_fill)
public val SparkIcons.KeyOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_key_outline)
public val SparkIcons.LockFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_lock_fill)
public val SparkIcons.MegaphoneFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_megaphone_fill)
public val SparkIcons.MegaphoneMuteFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_megaphone_mute_fill)
public val SparkIcons.MegaphoneMuteOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_megaphone_mute_outline)
public val SparkIcons.MegaphoneOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_megaphone_outline)
public val SparkIcons.Minus: DrawableRes get() = DrawableRes(R.drawable.spark_icons_minus)
public val SparkIcons.MobileCheck: DrawableRes get() = DrawableRes(R.drawable.spark_icons_mobile_check)
public val SparkIcons.MoveUp: DrawableRes get() = DrawableRes(R.drawable.spark_icons_move_up)
public val SparkIcons.Multimedia: DrawableRes get() = DrawableRes(R.drawable.spark_icons_multimedia)
public val SparkIcons.MultimediaSystem: DrawableRes get() = DrawableRes(R.drawable.spark_icons_multimedia_system)
public val SparkIcons.PaperMapFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_paper_map_fill)
public val SparkIcons.PaperMapOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_paper_map_outline)
public val SparkIcons.PenFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_pen_fill)
public val SparkIcons.PenOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_pen_outline)
public val SparkIcons.Percentage: DrawableRes get() = DrawableRes(R.drawable.spark_icons_percentage)
public val SparkIcons.PhoneFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_phone_fill)
public val SparkIcons.PhoneOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_phone_outline)
public val SparkIcons.PhotoPack: DrawableRes get() = DrawableRes(R.drawable.spark_icons_photo_pack)
public val SparkIcons.PiggyBankFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_piggy_bank_fill)
public val SparkIcons.PiggyBankOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_piggy_bank_outline)
public val SparkIcons.PinFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_pin_fill)
public val SparkIcons.PinOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_pin_outline)
public val SparkIcons.PlayFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_play_fill)
public val SparkIcons.Plus: DrawableRes get() = DrawableRes(R.drawable.spark_icons_plus)
public val SparkIcons.ProfileFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_profile_fill)
public val SparkIcons.ProfileOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_profile_outline)
public val SparkIcons.QuestionFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_question_fill)
public val SparkIcons.QuestionOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_question_outline)
public val SparkIcons.Refresh: DrawableRes get() = DrawableRes(R.drawable.spark_icons_refresh)
public val SparkIcons.RocketFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_rocket_fill)
public val SparkIcons.RocketOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_rocket_outline)
public val SparkIcons.RotateImage: DrawableRes get() = DrawableRes(R.drawable.spark_icons_rotate_image)
public val SparkIcons.Scan: DrawableRes get() = DrawableRes(R.drawable.spark_icons_scan)
public val SparkIcons.ShareFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_share_fill)
public val SparkIcons.ShareOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_share_outline)
public val SparkIcons.Shoes: DrawableRes get() = DrawableRes(R.drawable.spark_icons_shoes)
public val SparkIcons.ShoppingCartFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_shopping_cart_fill)
public val SparkIcons.ShoppingCartOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_shopping_cart_outline)
public val SparkIcons.Sort: DrawableRes get() = DrawableRes(R.drawable.spark_icons_sort)
public val SparkIcons.SpeedmeterFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_speedmeter_fill)
public val SparkIcons.SpeedmeterOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_speedmeter_outline)
public val SparkIcons.StarFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_star_fill)
public val SparkIcons.StarOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_star_outline)
public val SparkIcons.StoreFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_store_fill)
public val SparkIcons.StoreOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_store_outline)
public val SparkIcons.Sun: DrawableRes get() = DrawableRes(R.drawable.spark_icons_sun)
public val SparkIcons.TargetFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_target_fill)
public val SparkIcons.TargetOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_target_outline)
public val SparkIcons.ThreeSixty: DrawableRes get() = DrawableRes(R.drawable.spark_icons_three_sixty)
public val SparkIcons.Tractor: DrawableRes get() = DrawableRes(R.drawable.spark_icons_tractor)
public val SparkIcons.TrainFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_train_fill)
public val SparkIcons.TrainOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_train_outline)
public val SparkIcons.TrashFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_trash_fill)
public val SparkIcons.TrashOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_trash_outline)
public val SparkIcons.UnlockFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_unlock_fill)
public val SparkIcons.UnlockOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_unlock_outline)
public val SparkIcons.UserCheckFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_user_check_fill)
public val SparkIcons.UserCheckOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_user_check_outline)
public val SparkIcons.WarningFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_warning_fill)
public val SparkIcons.WarningOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_warning_outline)
public val SparkIcons.WorkFill: DrawableRes get() = DrawableRes(R.drawable.spark_icons_work_fill)
public val SparkIcons.WorkOutline: DrawableRes get() = DrawableRes(R.drawable.spark_icons_work_outline)
