name: '🔧 Icon hotfix: create branch'

on:
  pull_request:
    types: [closed]

concurrency:
  group: '${{ github.workflow }}-${{ github.event.pull_request.number }}'
  cancel-in-progress: true

jobs:
  create-hotfix-branch:
    if: |
      github.repository == 'leboncoin/spark-android' &&
      github.event.pull_request.merged == true &&
      github.event.pull_request.title == 'feat(icons): update icons' &&
      github.event.pull_request.user.login == 'github-actions[bot]'
    uses: ./.github/workflows/create-hotfix-branch.yml
    permissions:
      contents: write
    with:
      cherry_pick_sha: ${{ github.event.pull_request.merge_commit_sha }}
    secrets:
      PAT_SPARK: ${{ secrets.PAT_SPARK }}
