name: '📋 Publish Dokka to GitHub Pages'
run-name: "📋 Publish Dokka on ${{ inputs.ref }} to GitHub Pages by @${{ github.actor }}"

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch, tag, SHA, …'
        required: true
        default: 'main'
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    if: github.repository == 'leboncoin/spark-android'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}
          lfs: true
      - uses: ./.github/actions/setup-java
      - uses: ./.github/actions/setup-gradle
      - uses: ./.github/actions/setup-gradle-properties
      - name: Dokka
        run: ./gradlew dokkaGeneratePublicationHtml
      - uses: actions/configure-pages@v6.0.0
      - uses: actions/upload-pages-artifact@v5.0.0
        with:
          path: 'build/dokka'
      - id: deployment
        uses: actions/deploy-pages@v5.0.0
