name: '📦 Publish to Central Portal'

on:
  push:
    tags: ['*']
  workflow_dispatch:

jobs:
  publish:
    if: github.repository == 'leboncoin/spark-android'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-java
      - uses: ./.github/actions/setup-gradle
      - uses: ./.github/actions/setup-gradle-properties

      - name: '📦 Publish to Central Portal'
        run: ./gradlew publishAggregationToCentralPortal --no-configuration-cache
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CENTRAL_PORTAL_USERNAME: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
          CENTRAL_PORTAL_PASSWORD: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSWORD }}

      - name: '📦 Upload Maven artifact'
        uses: actions/upload-artifact@v5
        with:
          name: maven
          path: build/.m2/repository
