name: '🌈 GitHub Actions Security Analysis'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: {}

jobs:
  zizmor:
    name: '🌈 zizmor'
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: '🌈 Run zizmor'
        uses: zizmorcore/zizmor-action@0b77258cf93d4e0ae762c843422c333faf2793f6 # v0.5.2
